# Set prefix to ctrl + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Split with h and v into current path
bind-key h split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"

# Use Alt-arrow keys to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Shift arrow to switch windows
bind -n C-M-H previous-window # CTRL + Alt + h
bind -n C-M-L next-window # CTRL + Alt + l

set-option -g history-limit 4000

# Start numbering at 1
set -g base-index 1

# Mouse mode
setw -g mouse on

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Visual
set -g terminal-overrides ',xterm*:RGB'
set -g window-status-current-style "bold"

# Plugins
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'jamesoff/tmux-loadavg'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'xamut/tmux-weather'

# Theme
set -g @catppuccin_flavour 'macchiato' # latte,frappe, macchiato or mocha

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_left ""
set -g @catppuccin_status_modules_right "directory battery weather session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{b:pane_current_path}"
set-option -g @tmux-weather-location "São+Leopoldo"
set-option -g @tmux-weather-interval 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
