# Key bindings
# Set prefix to ctrl + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix
# Split with h and v into current path
bind-key h split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"
# Use Alt-arrow keys to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-l select-pane -D

# Shift arrow to switch windows
bind -n C-M-J previous-window # CTRL + Alt + h
bind -n C-M-K next-window # CTRL + Alt + l

set-option -g history-limit 4000

# Start numbering at 1
set -g base-index 1

# Mouse mode
set -g mouse-utf8 on
set -g mouse on

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Config
# History
set-option -g history-limit 4000
# Start numbering at 1
set -g base-index 1
# Mouse mode
set -g mouse on
# Visual
set -g terminal-overrides ',xterm*:RGB'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1'
set -g @plugin 'jamesoff/tmux-loadavg'
set -g @plugin 'tmux-plugins/tmux-battery'

# Theme (Catppuccin)
set -g @catppuccin_flavor 'macchiato' # latte,frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_status_background "#{@thm_bg}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"
set -g @catppuccin_window_current_text_color "#{@thm_crust}"

# Customize status text
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_number_position "right"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
