add_newline = false
# format = '$all$kubernetes$container$shell$character'
right_format='$kubernetes$gcloud'

[line_break]
disabled = false

[character]
format = "$symbol"
success_symbol = "[](bold green) "
error_symbol = "[](bold red) "

[aws]
symbol = " "
format = '| [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[directory]
read_only = " 󰋜"
home_symbol = "󰋜"

[docker_context]
symbol = " "

[gcloud]
symbol = " "
format = "| [$symbol$account(@$domain)(($region))]($style)"
# format = "[$symbol(($region))]($style)"

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[kubernetes]
disabled = false
format = "[$symbol$context( ($namespace))]($style) "
[kubernetes.context_aliases]
'arn:aws:eks:us-east-1:277048801940:cluster/gitlab' = 'gitlab-runners'

[lua]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

# [terraform]
# symbol = ""
# format = "via [$symbol $version]($style) "
