[module/date]
type = internal/date
interval = 1
date = %d/%m/%Y
label = %date%
label-foreground = ${colors.foreground}
label-font = 2

[module/time]
type = internal/date
interval = 1
time = %H:%M:%S
label = %time%
label-foreground = ${colors.foreground}
label-font = 2

[module/clock]
type = custom/text
format = %{T3}󰦖
format-foreground = ${colors.green}
; click-left = "~/Scripts/Calendar/calendar.sh"

[module/calendar]
type = custom/text
format = %{T3}󰸗
format-foreground = ${colors.green}
; click-left = "~/Scripts/Calendar/calendar.sh"
