#!/bin/bash

# Get weather information from wttr.in.
weather=$(curl -sS "wttr.in/São+Leopoldo?format=%C+%t+%h+%w")

# Extract the weather condition, temperature, and humidity using regular expressions.
condition=$(echo "$weather" | grep -oE '^[[:alpha:] ]+[[:alpha:]]')
temperature=$(echo "$weather" | grep -oE '[+-]?[0-9]+°C')
humidity=$(echo "$weather" | grep -oE '[0-9]+%')
wind=$(echo "$weather" | grep -oE '[0-9]+km/h')

# Select the appropriate icon according to the weather condition.
case $condition in
  "Clear"*) icon="󰖙 ";; #\uf305
  "Sunny"*) icon="󰖙 ";; #\uf305
  "Cloudy"*) icon="󰖐 ";; #\uf041
  "Mist"*) icon="󰖑 ";; #\uf74e
  "Fog"*) icon="󰖑 ";; #uf74e
  "Patchy rain nearby"*) icon="󰼳 ";; #\uf002
  "Light rain"*) icon="󰼳 ";; #\ue009
  "Partly rain"*) icon="󰼳 ";; #\ue009
  "Moderate rain"*) icon="󰖗 ";; #\ue009
  "Heavy rain"*) icon="󰙾 ";; #\uf02d
  "Overcast"*) icon=" ";; #\uf041
  *) icon=" ";; #\u2757
esac

case $1 in
  "icon")
    echo $icon
    ;;
  "temp")
    echo $temperature
    ;;
  "hum")
    echo $humidity
    ;;
  "wind")
    echo $wind
    ;;
  *)
  echo "$icon $temperature $humidity"
  ;;
esac
